export const styles = {
  container: { minHeight: '100vh', background: '#F7F5F2' },
  pageContainer: { padding: '24px 30px', maxWidth: 1300, margin: '0 auto' },
  title: { fontSize: 22, fontWeight: 700, color: '#1B6B2E', marginBottom: 16 },
  sidebar: { width: 260, background: '#1B6B2E', color: 'white', display: 'flex', flexDirection: 'column', height: '100vh', position: 'fixed' },
  card: { background: '#fff', borderRadius: 12, padding: 20, boxShadow: '0 1px 4px rgba(0,0,0,0.04)' },
  input: { padding: '10px 14px', border: '1.5px solid #e0e0e0', borderRadius: 8, fontSize: 13, width: '100%', outline: 'none', background: '#fff', transition: 'border 0.2s', fontFamily: 'inherit' },
  select: { padding: '10px 14px', border: '1.5px solid #e0e0e0', borderRadius: 8, fontSize: 13, width: '100%', outline: 'none', background: '#fff' },
  button: { padding: '12px 24px', background: '#1B6B2E', color: 'white', border: 'none', borderRadius: 8, cursor: 'pointer', fontSize: 14, fontWeight: 500 },
  buttonSecondary: { padding: '12px 24px', background: '#f5f5f5', color: '#6c757d', border: '1px solid #e0e0e0', borderRadius: 8, cursor: 'pointer', fontSize: 14, fontWeight: 500 },
  label: { display: 'block', fontSize: 12, fontWeight: 600, marginBottom: 6, color: '#333' },
  textarea: { padding: '10px 14px', border: '1.5px solid #e0e0e0', borderRadius: 8, fontSize: 13, width: '100%', outline: 'none', minHeight: 100, fontFamily: 'inherit', resize: 'vertical', background: '#fff' },
  badge: { display: 'inline-block', padding: '3px 10px', borderRadius: 12, fontSize: 11, fontWeight: 600 },
  table: { width: '100%', borderCollapse: 'collapse' },
  th: { padding: '10px 14px', textAlign: 'left', fontSize: 11, fontWeight: 700, color: '#888', borderBottom: '1px solid #eee', textTransform: 'uppercase', letterSpacing: 0.5 },
  td: { padding: '10px 14px', borderBottom: '1px solid #f5f5f5', fontSize: 13 },
  tab: { padding: '12px 24px', cursor: 'pointer', borderBottom: '2px solid transparent', marginBottom: -2, fontSize: 14, fontWeight: 500, color: '#6c757d' },
  tabActive: { padding: '12px 24px', cursor: 'pointer', borderBottom: '2px solid #1B6B2E', marginBottom: -2, fontSize: 14, fontWeight: 600, color: '#1B6B2E' },
};
